spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_old?serverTimezone=GMT&characterEncoding=UTF8
    username: root
    password: 19980220
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - /mapper/project/*.xml
server:
  port: 80