server:
  port: 80
debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop1905
    driver-class-name: com.mysql.jdbc.Driver
    password: 19980220
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/
    
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
